language: smalltalk
sudo: false
os:
  - linux
smalltalk:
  - Pharo64-7.0
  - Pharo-7.0
  - Pharo-6.1
matrix:
  allow_failures:
  - smalltalk: Pharo64-7.0
  - smalltalk: Pharo-7.0
  fast_finish: true
before_deploy:
  - cp "${SMALLTALK_CI_IMAGE}" "Mole.image"
  - cp "${SMALLTALK_CI_CHANGES}" "Mole.changes"
  - zip -q "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip" "Mole.image" "Mole.changes"
deploy:
  provider: releases
  api_key:
    secure: mRoJUKUQh6g2L0HhP51Leg6EKwVdXxclEjsC9ZSMooEVmQseftE/QNpW4D2bViI1ZE9pMRuUFoFvxRn0ZfruIFGT8fCo4Df+QY4HUDueWsj2m4zfuAzuibGvLCH+44W5IBdcv37dRDsS7lNOZg8lOkzJEMqrecLFH91jdLovomITNaPl06EJ4kP49V7xZtHkMeHHTjW7m7JhcJVIHHoTlQxNbpoRLUGrCjFKZToyXeMmkE5KZLM3rJVgsN8ja/CBLtarVSz4hRaQmRSxktoaKdK01eRWCk2WDvjMmizdhb9W9NQbw9pXpVXW1l2cB3xdZraatOSHXan2SpnhGfHymYDQQMLH03Gof61jGEB08SqGZRHnpcGU781raGbheXzPxlg9DJSsWz1893NFi4ztAwaSsvhl3DibeGjG9pCn4vf4op9DEu+9tQIdJBqtE7rjPbBArnncE6FA7ZnoZ0ZbnDb2X+0kE6S5AjuZPEFNS1Xiqo/zd1uJNCk10L9d6QO2oDDf6iyYKchJIksgN8i5qkzEqLYiXeTDY25LfZytvuIOUu5nYtSHD/HHx4W7Xo8AfxiLM7pQUCnuqxj9XmROBwRGXHmLfm5cGkveuzOjvmhs3Pt4ExQLhXyv45fxwOxAUsCPLrJoVDwZ/mmDyAyXQwzkmUnMTH5bJ/665/CGhAY=
  file: "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip"
  skip_cleanup: true
  on:
    repo: ba-st/Mole
    tags: true
